# Generated by Django 5.0.6 on 2024-05-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام روش پرداخت')),
                ('method', models.CharField(max_length=100, verbose_name='نوع پرداخت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات روش پرداخت')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت ها',
            },
        ),
    ]
