# Generated by Django 5.0.6 on 2024-05-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='روش حمل و نقل')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='هزینه حمل و نقل')),
                ('delivery_time', models.IntegerField(verbose_name='زمان تحویل/روز')),
            ],
            options={
                'verbose_name': 'حمل و نقل',
                'verbose_name_plural': 'حمل و نقل ها',
            },
        ),
    ]
